#!/bin/bash

PROCESSUS="$1"
if [ "$PROCESSUS" = "" ] ; then
        ps -eo size,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }'
else
 echo -e "$PROCESSUS:\c"; ps -eo size,pid,command | grep $PROCESSUS | awk 'BEGIN {sum=0} {sum=sum+$1;} END {printf("%13.2f Mb\n", sum / 1024)}'
fi
